name: 构建并部署 Hugo 网站

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.103.0
    steps:
      - name: 安装 Hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb

      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 安装 Dart Sass
        run: sudo snap install dart-sass

      - name: 安装依赖
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: 构建 Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify

      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./public
